# Generated by Django 2.0 on 2022-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('rating', models.IntegerField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
