# Generated by Django 2.0 on 2022-09-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_auto_20220912_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='date',
            field=models.DateField(),
        ),
    ]
